services:
  app:
    restart: always
    build:
      context: .
    ports:
      - 444:8000
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
    # --ssl-keyfile=./cert/key.txt 
    # --ssl-certfile=./cert/certificate.txt
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./front:/app/front
      # - c:\wamp64\bin\apache\apache2.4.59\conf\ssl\:/app/cert
