services:
  app:
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
